## Automate Writing the connection message

In [18]:
import pandas as pd
import numpy as np

data = pd.read_csv('./Data/data.csv')
data.head()# split the name into first and last name for the first name column
greet_message = "Hi, [firstname]! I am Ken, the co-founder at Esger, an NYC startup. We just raised $250k+ and support from top institutions like Cornell, Microsoft, and ERA. As we are using AI to tackle the heart of sustainability issues, the supply chain, I love to connect with experts in the field (like you!)."

data['first_name'] = data['Name'].apply(lambda x: x.split(' ')[0] if type(x) == str else np.nan)
data['greet_message'] = data['first_name'].apply(lambda x: greet_message.replace('[firstname]', x) if type(x) == str else np.nan)

data = data[["Name",'By','greet_message']]

data.to_csv('./Data/processed_data.csv', index=False)

## Automate Outputing the name of linkedin Contact

In [23]:
import pandas as pd
import numpy as np
import re

by_who = "Ken"

greet_message = "Hi, [firstname]! I am Ken, the co-founder at Esger, an NYC startup. We just raised $250k+ and support from top institutions like Cornell, Microsoft, and ERA. As we are using AI to tackle the heart of sustainability issues, the supply chain, I love to connect with experts in the field (like you!)."

input_string = '''https://www.linkedin.com/in/melissa-mardarie-53364117/ | (1) Melissa Mardarie | LinkedIn
https://www.linkedin.com/in/na-yang-977b7b8/ | (1) NA YANG | LinkedIn
'''


def remove_special_characters_and_numbers(input_str):
    # Remove all characters that are not alphabets
    clean_str = re.sub(r'[^a-zA-Z\s]', '', input_str)
    return clean_str

# Initialize an empty list to store the names
names_list = []
url_list = []
# Split the input string by lines
for line in input_string.split("\n"):
    # Split each line by the '|' character
    parts = line.split(" | ")

    # The name is the second element in the 'parts' list, strip leading and trailing whitespaces
    url = parts[0].strip()
    name = remove_special_characters_and_numbers(parts[1]).strip()
    
    # Append the name to the list
    names_list.append(name)
    url_list.append(url)


output = pd.DataFrame({"Name":names_list, "Who?":by_who, "LinkedIn Profile":url_list})
output['greet_message'] = output['Name'].apply(lambda x: greet_message.replace('[firstname]', x.split(' ')[0]) if type(x) == str else np.nan)

output.to_csv("./Data/outreach_parsed.csv", index=False)

In [24]:
output

,Name,Who?,LinkedIn Profile,greet_message
0,Melissa Mardarie,Ken,https://www.linkedin.com/in/melissa-mardarie-5...,"Hi, Melissa! I am Ken, the co-founder at Esger..."
1,NA YANG,Ken,https://www.linkedin.com/in/na-yang-977b7b8/,"Hi, NA! I am Ken, the co-founder at Esger, an ..."
2,Manu Kumra,Ken,https://www.linkedin.com/in/manu-kumra-376a2246/,"Hi, Manu! I am Ken, the co-founder at Esger, a..."
3,Cindy Carter,Ken,https://www.linkedin.com/in/cindylcarter/,"Hi, Cindy! I am Ken, the co-founder at Esger, ..."
4,Tyler Feigenbaum,Ken,https://www.linkedin.com/in/tyler-feigenbaum-0...,"Hi, Tyler! I am Ken, the co-founder at Esger, ..."
...,...,...,...,...
96,Maria Forney,Ken,https://www.linkedin.com/in/mariaforney/,"Hi, Maria! I am Ken, the co-founder at Esger, ..."
97,Michelle D,Ken,https://www.linkedin.com/in/d-michelle/,"Hi, Michelle! I am Ken, the co-founder at Esge..."
98,David Siddiqui,Ken,https://www.linkedin.com/in/davidsiddiqui/,"Hi, David! I am Ken, the co-founder at Esger, ..."
99,Johnna Humbert,Ken,https://www.linkedin.com/in/johnna-humbert/,"Hi, Johnna! I am Ken, the co-founder at Esger,..."
100,Ian Murty,Ken,https://www.linkedin.com/in/ian-murty-77a23220/,"Hi, Ian! I am Ken, the co-founder at Esger, an..."

In [27]:
import webbrowser
url_list = output['LinkedIn Profile'].tolist()
for url in url_list:
    webbrowser.open(url, new=2)